name: '2. Build and Push Agent Image to Repository'

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    environment: azdo
    permissions:
      id-token: write
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - uses: 'azure/login@v1'
        name: 'Login to Azure'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.44.1
          inlineScript: |
            acrName="${{vars.RESOURCE_PREFIX}}acr"
            az acr build -r $acrName -t "azdo-build-agent:latest" -t "azdo-build-agent:${{ github.run_id }}" "./src/azdo_build_agent"
