name: '3. Build and Push Agent Helm Chart to Repository'

on:
  workflow_dispatch:

env:
  HELM_APP_VERSION: "1.0.${{ github.run_id }}"
  HELM_CHART_VERSION: "1.0.${{ github.run_id }}"
  HELM_CHART_NAME: scaled-azdo-build-agent

jobs:
  build_image:
    runs-on: ubuntu-latest
    environment: azdo
    permissions:
      id-token: write
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - uses: 'azure/login@v1'
        name: 'Login to Azure'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      - uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.44.1
          inlineScript: |
            acrName="${{vars.RESOURCE_PREFIX}}acr"
            echo "ACRNAME=$( echo $acrName )" >> $GITHUB_ENV
            accessToken = $(az acr login --name "$acrName" --expose-token --query accessToken -o tsv)
            echo "ACCESSTOKEN=$(echo $accessToken)" >> $GITHUB_ENV
      - name: helm package and push
        run: |
          echo ${{ env.ACRNAME }} 
          helm package "./helm/scaled-azdo-build-agent" --app-version "${{env.HELM_APP_VERSION}}" --version "${{env.HELM_CHART_VERSION}}"
          echo ${{ env.ACCESSTOKEN }} | helm registry login --username "00000000-0000-0000-0000-000000000000" --password-stdin "$acrName.azurecr.io"
          helm push "${{env.HELM_CHART_NAME}}-${{env.HELM_CHART_VERSION}}.tgz" "oci://${{ env.ACRNAME}}.azurecr.io"
