name: '4. Deploy Agent Pool'

on:
  workflow_dispatch:

env:
  HELM_APP_VERSION: "1.0.${{ github.run_id }}"
  HELM_CHART_VERSION: "1.0.${{ github.run_id }}"
  HELM_CHART_NAME: scaled-azdo-build-agent
  ACRNAME: "${{vars.RESOURCE_PREFIX}}acr"
  AKSNAME: "${{vars.RESOURCE_PREFIX}}-aks"
  RESOURCEGROUP: "${{vars.RESOURCE_PREFIX}}-rg"
jobs:
  build_image:
    runs-on: ubuntu-latest
    environment: azdo
    permissions:
      id-token: write
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      - uses: 'azure/login@v1'
        name: 'Login to Azure'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: installhelm
      - name: deploy helm chart
        run: |
          az aks get-credentials --name "${{ env.AKSNAME }}" --resource-group "${{ env.RESOURCEGROUP }}"
          helm version
