apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azdo-build-agent.fullname" . }}-secret-docker
  namespace: {{ include "azdo-build-agent.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}